
name: 'install_dependencies'
description: 'Install system dependencies required by the project'

runs:
  using: "composite"
  steps:
    - name: Install Ubuntu Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Make sure sudo is installed before running sudo calls
        apt update
        apt install sudo -y 
        sudo apt-get update
        sudo apt-get install xorg-dev dialog -y

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Unlink and re-link to prevent errors when github mac runner images
        # install python outside of brew, for example:
        # https://github.com/orgs/Homebrew/discussions/3895
        # https://github.com/actions/setup-python/issues/577
        # https://github.com/actions/runner-images/issues/6459
        # https://github.com/actions/runner-images/issues/6507
        # https://github.com/actions/runner-images/issues/2322
        brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
        brew update
        brew install xorg-server