function(Evie_enable_coverage project_name)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    target_compile_options(${project_name} INTERFACE --coverage -O0 -g -fno-inline -fno-inline-small-functions -fno-default-inline)
    target_link_options(${project_name} INTERFACE --coverage)
  endif()
endfunction()
